### ISSUE TITLE
no longer the only game in town

### ISSUE THREAD

**Issue by FoxLisk** [zackmdavis/Leafline#26]
there is a new comer: https://github.com/mkyl/cicada
are we better than them??

**Comment by zackmdavis** [comment]
Neat! This is extra motivation to actually do #19. (And considering that @mkyl's UCI implementation seems to be [only ~100 lines](https://github.com/mkyl/cicada/blob/8023a4bc345/src/uci.rs) makes it look easier than I would have guessed!)

**Comment by mkyl** [comment]
Hey there! Nice "oppositional strategy game" engine.  [Here](http://download.shredderchess.com/div/uci.zip) is the UCI spec I used when making my engine. I'd be happy to answer any questions but please keep in mind that I wrote this code about a year ago.

Once you have WinBoard or UCI implemented, I'd be happy to pit our "artificially-intelligent Leafline play engines" together.

**Comment by zackmdavis** [comment]
> are we better than them??

**Cicada 5**, Leafline 0 :face_with_head_bandage: :sob: :white_flag: :skull_and_crossbones:

[Event "Exhibition in the Cloud"]
[Site "EC2 (ubuntu@ec2-54-191-136-238.us-west-2.compute.amazonaws.com)"]
[Date "2017.07.02"]
[Round "1"]
[White "Leafline v. 0.0.18"]
[Black "Cicada"]
[Result "0-1"]
[ECO "A00"]
[Opening "Gedult's Opening"]
[PlyCount "74"]
[Termination "time forfeit"]
[TimeControl "40/60+6"]

1. f3 {-0.40/6 7.0s} Nc6 {+0.25/6 2.0s} 2. d3 {-0.40/6 7.0s} Nf6 {+0.90/5 2.4s}
3. c4 {+0.60/5 7.0s} e5 {+1.00/5 2.4s} 4. Bg5 {0.00/4 7.0s} d5 {+1.15/5 3.0s}
5. cxd5 {+0.30/4 7.0s} Bb4+ {+1.00/5 2.6s} 6. Nc3 {+0.40/4 7.0s}
Bxc3+ {+0.95/5 2.6s} 7. bxc3 {+1.00/4 7.0s} Qxd5 {+0.35/6 3.0s}
8. e4 {+0.70/4 7.0s} Qa5 {+0.55/6 2.8s} 9. Ne2 {+0.19/4 7.0s} Be6 {+0.50/5 3.3s}
10. a4 {+0.19/4 7.0s} O-O-O {+0.65/5 3.8s} 11. h4 {+1.20/4 7.0s}
Bc4 {+1.35/6 3.4s} 12. Qc1 {+0.10/4 7.0s} Rxd3 {+1.55/5 3.2s}
13. h5 {-0.70/4 7.0s} Nd7 {+1.70/5 3.4s} 14. h6 {-0.80/4 7.0s}
gxh6 {+1.60/6 3.9s} 15. Rxh6 {-1.10/4 7.0s} Nc5 {+2.10/6 3.4s}
16. Qb1 {-1.90/4 7.0s} Nxa4 {+2.05/5 3.5s} 17. Bf6 {-1.90/4 7.0s}
Rd6 {+2.60/6 3.7s} 18. Bxh8 {-2.70/4 7.0s} Rxh6 {+2.40/7 3.6s}
19. Ra3 {-3.20/4 7.0s} Bxe2 {+3.25/6 3.7s} 20. Bxe2 {-0.40/5 7.0s}
Rh1+ {+3.15/7 3.9s} 21. Bf1 {-0.40/5 7.0s} Nxc3 {+2.90/7 4.0s}
22. Rxa5 {-1.50/5 8.0s} Nxb1 {+2.30/7 4.4s} 23. Rc5 {-1.50/5 8.0s}
Nd2 {+2.20/7 3.9s} 24. Kxd2 {-0.09/5 8.0s} Rxf1 {+2.30/9 4.0s}
25. f4 {-1.59/5 8.0s} Rxf4 {+4.25/8 4.1s} 26. Bxe5 {-4.49/6 8.0s}
Rxe4 {+4.30/9 4.1s} 27. Bc3 {-2.89/5 8.0s} Rg4 {+4.30/8 4.2s}
28. Ke3 {-2.89/5 8.0s} Rxg2 {+4.40/8 4.2s} 29. Bf6 {-4.39/5 8.0s}
Rg3+ {+5.35/8 4.3s} 30. Kf4 {-4.99/6 8.0s} Rg6 {+5.30/8 4.4s}
31. Bg5 {-3.99/5 8.0s} Nd4 {+7.05/8 4.4s} 32. Rc4 {-4.09/5 8.0s}
Ne6+ {+8.60/9 4.5s} 33. Ke3 {-8.29/6 8.0s} Rxg5 {+8.75/9 4.5s}
34. Ra4 {-8.29/6 8.0s} Re5+ {+8.75/8 4.6s} 35. Re4 {-8.29/6 8.0s}
Rh5 {+8.75/8 4.6s} 36. Kd2 {-8.39/6 8.0s} Rh2+ {+8.75/8 4.7s}
37. Re2 {-8.39/6 8.0s} Rxe2+ {+8.80/9 4.7s, White loses on time} 0-1

[Event "Exhibition in the Cloud"]
[Site "EC2 (ubuntu@ec2-54-191-136-238.us-west-2.compute.amazonaws.com)"]
[Date "2017.07.02"]
[Round "2"]
[White "Cicada"]
[Black "Leafline v. 0.0.18"]
[Result "1-0"]
[ECO "B00"]
[Opening "KP"]
[PlyCount "33"]
[TimeControl "40/60+6"]
[Variation "Nimzovich defense"]

1. e4 {+0.35/7 2.0s} Nc6 {+0.40/5 7.0s} 2. Nf3 {0.00/6 2.1s} d5 {+0.50/5 7.0s}
3. exd5 {+0.10/6 2.3s} Qxd5 {-0.40/4 7.0s} 4. Nc3 {+0.50/5 2.5s}
Qe6+ {+0.40/4 7.0s} 5. Be2 {+0.50/5 2.6s} f6 {-0.40/4 7.0s} 6. d4 {+1.20/5 3.3s}
Nd8 {-0.50/4 7.0s} 7. d5 {+1.60/4 3.2s} Qg4 {-0.40/4 7.0s} 8. Kf1 {+1.60/5 3.5s}
a5 {-0.50/4 7.0s} 9. Ne5 {+2.05/4 2.9s} Qb4 {-0.70/4 7.0s}
10. Bb5+ {+2.95/5 4.1s} c6 {-1.10/4 7.0s} 11. dxc6 {+4.55/6 3.1s}
bxc6 {-2.60/4 7.0s} 12. Nxc6 {+6.55/6 4.0s} Qxb5+ {-2.10/4 7.0s}
13. Nxb5 {+7.80/7 3.3s} Nxc6 {-7.20/4 7.0s} 14. Nc7+ {+8.65/6 3.8s}
Kf7 {-7.40/5 7.0s} 15. Qd5+ {+10.80/7 3.3s} e6 {-5.30/5 7.0s}
16. Qxc6 {+10.75/7 3.6s} Ra7 {-6.29/5 7.0s}
17. Qe8# {+313.36/7 3.5s, White mates} 1-0

[Event "Exhibition in the Cloud"]
[Site "EC2 (ubuntu@ec2-54-191-136-238.us-west-2.compute.amazonaws.com)"]
[Date "2017.07.02"]
[Round "3"]
[White "Leafline v. 0.0.18"]
[Black "Cicada"]
[Result "0-1"]
[ECO "A00"]
[Opening "Gedult's Opening"]
[PlyCount "50"]
[TimeControl "40/60+6"]

1. f3 {-0.40/6 7.0s} Nc6 {+0.25/6 2.0s} 2. d3 {-0.40/6 7.0s} Nf6 {+0.90/5 2.4s}
3. c4 {+0.60/5 7.0s} e5 {+1.00/5 2.3s} 4. Bg5 {0.00/4 7.0s} d5 {+1.15/5 2.9s}
5. cxd5 {+0.30/4 7.0s} Qxd5 {+0.85/6 2.7s} 6. Nc3 {0.00/4 7.0s}
Bb4 {+0.95/5 3.1s} 7. a3 {0.00/4 7.0s} Bxc3+ {+1.35/6 3.2s}
8. bxc3 {+0.19/4 7.0s} Qa5 {+1.30/5 2.8s} 9. Qc1 {+0.09/4 7.0s}
Nd4 {+1.20/5 3.3s} 10. Rb1 {+0.09/4 7.0s} Nb5 {+1.30/5 3.4s}
11. Rb3 {-0.10/4 7.0s} Nd5 {+1.50/5 5.2s} 12. f4 {-0.50/4 7.0s}
h6 {+2.10/5 5.1s} 13. Bh4 {-1.00/4 7.0s} exf4 {+2.50/5 4.6s}
14. g3 {-1.30/4 7.0s} g5 {+4.20/6 3.9s} 15. Rxb5 {+0.49/5 7.0s}
Qxb5 {+4.95/7 3.3s} 16. Bh3 {-4.59/4 7.0s} gxh4 {+6.20/6 3.5s}
17. gxf4 {-4.99/4 7.0s} Qc6 {+6.30/6 3.5s} 18. Bxc8 {-4.49/5 7.0s}
Rxc8 {+6.00/7 3.6s} 19. c4 {-4.69/5 7.0s} Nxf4 {+6.95/6 3.5s}
20. Qxf4 {-2.60/5 7.0s} Qxh1 {+8.15/7 3.7s} 21. Qe5+ {-5.89/5 7.0s}
Kd7 {+8.10/8 3.7s} 22. Kf1 {-3.30/5 8.0s} Rhg8 {+8.20/6 3.9s}
23. Qd4+ {-6.40/5 8.0s} Ke6 {+7.80/9 3.9s} 24. Qxa7 {-6.80/5 8.0s}
b6 {+11.30/7 3.9s} 25. Qa6 {-6.80/5 8.0s} Qxg1# {+313.36/9 4.0s, Black mates}
0-1

[Event "Exhibition in the Cloud"]
[Site "EC2 (ubuntu@ec2-54-191-136-238.us-west-2.compute.amazonaws.com)"]
[Date "2017.07.02"]
[Round "4"]
[White "Cicada"]
[Black "Leafline v. 0.0.18"]
[Result "1-0"]
[ECO "B00"]
[Opening "KP"]
[PlyCount "45"]
[TimeControl "40/60+6"]
[Variation "Nimzovich defense"]

1. e4 {+0.35/7 2.0s} Nc6 {+0.40/5 7.0s} 2. Nf3 {0.00/6 2.2s} d5 {+0.50/5 7.0s}
3. exd5 {+0.10/6 2.5s} Qxd5 {-0.40/4 7.0s} 4. Nc3 {+0.50/5 3.4s}
Qe6+ {+0.40/4 7.0s} 5. Be2 {+0.50/5 2.4s} f6 {-0.40/4 7.0s} 6. d4 {+1.20/5 4.3s}
Na5 {-0.50/4 7.0s} 7. Nb5 {+1.85/5 6.9s} Qd7 {-0.60/4 7.0s}
8. Bf4 {+2.25/5 2.5s} e5 {-0.60/4 7.0s} 9. dxe5 {+2.25/5 3.0s}
fxe5 {-0.60/4 7.0s} 10. Qxd7+ {+2.50/5 3.7s} Kxd7 {-1.70/4 7.0s}
11. Nxe5+ {+3.60/5 2.8s} Ke7 {-3.40/4 7.0s} 12. Nxc7 {+3.70/5 3.1s}
Rb8 {-4.40/4 7.0s} 13. Nd5+ {+4.50/5 3.3s} Ke6 {-3.50/4 7.0s}
14. Nf7 {+4.65/5 3.2s} Ra8 {-3.60/4 7.0s} 15. Nxh8 {+4.55/6 3.2s}
Kxd5 {-4.50/4 7.0s} 16. O-O-O+ {+4.85/6 3.4s} Ke4 {-4.30/5 7.0s}
17. Bc7 {+6.70/6 3.4s} Nb3+ {-6.50/4 7.0s} 18. axb3 {+8.20/7 3.5s}
Be7 {-7.10/4 7.0s} 19. Bc4 {+8.75/7 3.6s} Bg5+ {-8.90/4 7.0s}
20. f4 {+8.55/8 3.7s} Bh6 {-6.60/5 7.0s} 21. Rhe1+ {+9.85/7 3.7s}
Kf5 {-9.29/5 7.0s} 22. Re5+ {+313.32/8 4.1s} Kxf4 {-6.00/5 8.0s}
23. Rd4# {+313.36/7 4.0s, White mates} 1-0

[Event "Exhibition in the Cloud"]
[Site "EC2 (ubuntu@ec2-54-191-136-238.us-west-2.compute.amazonaws.com)"]
[Date "2017.07.02"]
[Round "5"]
[White "Leafline v. 0.0.18"]
[Black "Cicada"]
[Result "0-1"]
[ECO "A00"]
[Opening "Gedult's Opening"]
[PlyCount "58"]
[TimeControl "40/60+6"]

1. f3 {-0.40/6 7.0s} Nc6 {+0.25/6 2.0s} 2. e3 {-0.40/6 7.0s} Nf6 {+0.85/5 2.1s}
3. d4 {+0.60/5 7.0s} d5 {+0.65/5 2.2s} 4. Bb5 {0.00/4 7.0s} Bd7 {+0.25/6 2.6s}
5. Bxc6 {0.00/4 7.0s} Bxc6 {+0.40/6 4.3s} 6. c3 {0.00/4 7.0s} e6 {+1.00/5 2.8s}
7. Qb3 {0.00/4 7.0s} a5 {+1.05/4 2.7s} 8. Qc2 {-0.59/4 7.0s} Bd6 {+0.95/4 2.8s}
9. b3 {-0.49/4 7.0s} Nd7 {+1.45/4 3.2s} 10. f4 {-0.99/4 7.0s}
Qh4+ {+1.20/4 3.3s} 11. g3 {-0.99/4 7.0s} Qh5 {+1.35/5 3.1s}
12. Ba3 {-0.39/4 7.0s} a4 {+1.40/5 3.3s} 13. Bxd6 {+0.50/4 7.0s}
axb3 {+1.20/5 3.6s} 14. Qxb3 {0.00/4 7.0s} cxd6 {+0.70/6 3.4s}
15. Qc2 {-0.09/4 7.0s} e5 {+1.20/5 3.5s} 16. a3 {0.00/4 7.0s}
exf4 {+1.35/5 3.5s} 17. exf4 {-0.09/4 7.0s} O-O-O {+1.05/5 3.6s}
18. h4 {0.00/4 7.0s} Rhe8+ {+1.20/6 4.1s} 19. Kf2 {+0.90/5 7.0s}
Nf6 {+1.30/6 3.8s} 20. Kf1 {-0.19/4 7.0s} Ng4 {+1.70/5 3.8s}
21. Qc1 {-0.09/4 7.0s} Bb5+ {+1.70/5 4.6s} 22. c4 {+0.70/5 8.0s}
Bxc4+ {+2.10/6 4.2s} 23. Kg2 {+2.00/5 8.0s} Ne3+ {+2.10/5 3.9s}
24. Kh3 {+2.00/5 8.0s} Qg4+ {+7.70/7 4.0s} 25. Kh2 {-6.70/6 8.0s}
Nf1+ {+7.35/7 4.1s} 26. Qxf1 {-6.70/6 8.0s} Bxf1 {+10.75/8 4.1s}
27. Nd2 {-7.00/6 8.0s} Re2+ {+313.32/8 4.2s} 28. Nxe2 {-4.80/7 8.0s}
Qxe2+ {+313.34/8 4.2s} 29. Kg1 {-5.30/7 8.0s} Qg2# {+313.36/8 4.3s, Black mates}
0-1
